### PR TITLE
import_helper.php: Error in line #210

### PR DESCRIPTION
**Pull request by fvanderstarre**
"switchMSSQLIdentityInsert('questions',true) replaced by "switchMSSQLIdentityInsert('questions',false)""on line #210

### CODE REVIEW

**Comment by Shnoulle** [comment]
Have an error ?

**Comment by fvanderstarre** [comment]
Yes, true = false .... :-s

**Comment by Shnoulle** [comment]
? true != false

But : what error you have in mssql ?

**Comment by fvanderstarre** [comment]
What I meant to say was: I made an error on line 210 in application/helpers/admin/import_helper.php, and to correct it I changed 'true' to 'false' there. OK?

**Comment by Shnoulle** [comment]
Arg it's the state … set to true, and after set to false …
OK :) right :)

**Pull request merged**
